server "pie.symmachus.org" {
	log style combined
	listen on $listen_addr port 80
	root "/vhosts/pie.symmachus.org/htdocs"
	location "*.svg" {
		default type image/svg+xml
	}
	location "/feed.xml" {
		default type application/rss+xml
	}
	location "/sitemap.xml" {
		default type application/xml
	}
}

server "esperanto.symmachus.org" {
	log style combined
	listen on $listen_addr port 80
	root "/vhosts/esperanto.symmachus.org/htdocs"
	location "*.svg" {
		default type image/svg+xml
	}
	location "/feed.xml" {
		default type application/rss+xml
	}
	location "/sitemap.xml" {
		default type application/xml
	}
}

server "toki.symmachus.org" {
	log style combined
	listen on $listen_addr port 80
	root "/vhosts/toki.symmachus.org/htdocs"
	location "*.svg" {
		default type image/svg+xml
	}
	location "/feed.xml" {
		default type application/rss+xml
	}
	location "/sitemap.xml" {
		default type application/xml
	}
}

server "solresol.symmachus.org" {
	log style combined
	listen on $listen_addr port 80
	root "/vhosts/solresol.symmachus.org/htdocs"
	location "*.svg" {
		default type image/svg+xml
	}
	location "/feed.xml" {
		default type application/rss+xml
	}
	location "/sitemap.xml" {
		default type application/xml
	}
}
