server "pie.symmachus.org" {
	log style combined
	listen on $listen_addr port 80
	root "/vhosts/pie.symmachus.org/htdocs"
}

server "esperanto.symmachus.org" {
	log style combined
	listen on $listen_addr port 80
	root "/vhosts/esperanto.symmachus.org/htdocs"
}

server "toki.symmachus.org" {
	log style combined
	listen on $listen_addr port 80
	root "/vhosts/toki.symmachus.org/htdocs"
}

server "solresol.symmachus.org" {
	log style combined
	listen on $listen_addr port 80
	root "/vhosts/solresol.symmachus.org/htdocs"
}
